# Análise do algoritmo Selection Sort

## Implementação

In [1]:
import pandas as pd

def selection_sort(A):
    A = A.copy()
    n = len(A)
    passos = []
    comparacoes = 0
    trocas = 0

    for i in range(n - 1):
        indice_minimo = i
        for j in range(i + 1, n):
            comparacoes += 1
            passos.append({
                'i': i,
                'j': j,
                'menor_atual': A[indice_minimo],
                'comparando_com': A[j],
                'vetor': A.copy(),
                'operação': f'comparar A[{j}] com A[{indice_minimo}]'
            })
            if A[j] < A[indice_minimo]:
                indice_minimo = j

        if indice_minimo != i:
            A[i], A[indice_minimo] = A[indice_minimo], A[i]
            trocas += 1
            passos.append({
                'i': i,
                'j': indice_minimo,
                'menor_atual': A[i],
                'comparando_com': '-',
                'vetor': A.copy(),
                'operação': f'trocar A[{i}] com A[{indice_minimo}]'
            })

    return A, passos, comparacoes, trocas

## Execução

In [2]:
A = [29, 10, 14, 37, 13]
ordenado, passos, comparacoes, trocas = selection_sort(A)

print('Vetor original:', A)
print('Vetor ordenado:', ordenado)
print('Comparações:', comparacoes)
print('Trocas:', trocas)

display(pd.DataFrame(passos))

Vetor original: [29, 10, 14, 37, 13]
Vetor ordenado: [10, 13, 14, 29, 37]
Comparações: 10
Trocas: 3

    i  j  ...                 vetor                operação
0   0  1  ...  [29, 10, 14, 37, 13]  comparar A[1] com A[0]
1   0  2  ...  [29, 10, 14, 37, 13]  comparar A[2] com A[1]
2   0  3  ...  [29, 10, 14, 37, 13]  comparar A[3] com A[1]
3   0  4  ...  [29, 10, 14, 37, 13]  comparar A[4] com A[1]
4   0  1  ...  [10, 29, 14, 37, 13]    trocar A[0] com A[1]
5   1  2  ...  [10, 29, 14, 37, 13]  comparar A[2] com A[1]
6   1  3  ...  [10, 29, 14, 37, 13]  comparar A[3] com A[2]
7   1  4  ...  [10, 29, 14, 37, 13]  comparar A[4] com A[2]
8   1  4  ...  [10, 13, 14, 37, 29]    trocar A[1] com A[4]
9   2  3  ...  [10, 13, 14, 37, 29]  comparar A[3] com A[2]
10  2  4  ...  [10, 13, 14, 37, 29]  comparar A[4] com A[2]
11  3  4  ...  [10, 13, 14, 37, 29]  comparar A[4] com A[3]
12  3  4  ...  [10, 13, 14, 29, 37]    trocar A[3] com A[4]

[13 rows x 6 columns]

## Tabela N, comparações e trocas

In [3]:
linhas = []
for n in range(2, 11):
    A = list(range(n, 0, -1))
    _, _, comparacoes, trocas = selection_sort(A)
    linhas.append({'N': n, 'Comparações': comparacoes, 'Trocas': trocas})

display(pd.DataFrame(linhas))

    N  Comparações  Trocas
0   2            1       1
1   3            3       1
2   4            6       2
3   5           10       2
4   6           15       3
5   7           21       3
6   8           28       4
7   9           36       4
8  10           45       5