# Complexidade assintótica e MergeSort

## Implementação

In [1]:
import pandas as pd

class ContadorMergeSort:
    def __init__(self):
        self.chamadas = 0
        self.comparacoes = 0
        self.escritas = 0
        self.passos = []


def merge_sort(A, inicio=0, fim=None, contador=None):
    if fim is None:
        fim = len(A) - 1
    if contador is None:
        contador = ContadorMergeSort()

    contador.chamadas += 1

    if inicio < fim:
        meio = (inicio + fim) // 2
        contador.passos.append({
            'chamada': f'MERGE_SORT({inicio}, {fim})',
            'meio': meio,
            'subvetor': A[inicio:fim+1].copy(),
            'operação': 'dividir'
        })

        merge_sort(A, inicio, meio, contador)
        merge_sort(A, meio + 1, fim, contador)
        merge(A, inicio, meio, fim, contador)

    return A, contador


def merge(A, inicio, meio, fim, contador):
    esquerda = A[inicio:meio + 1]
    direita = A[meio + 1:fim + 1]

    i = 0
    j = 0
    k = inicio

    while i < len(esquerda) and j < len(direita):
        contador.comparacoes += 1
        if esquerda[i] <= direita[j]:
            A[k] = esquerda[i]
            i += 1
        else:
            A[k] = direita[j]
            j += 1
        contador.escritas += 1
        contador.passos.append({
            'chamada': f'MERGE({inicio}, {meio}, {fim})',
            'meio': meio,
            'subvetor': A[inicio:fim+1].copy(),
            'operação': f'escrever em A[{k}]'
        })
        k += 1

    while i < len(esquerda):
        A[k] = esquerda[i]
        contador.escritas += 1
        i += 1
        k += 1

    while j < len(direita):
        A[k] = direita[j]
        contador.escritas += 1
        j += 1
        k += 1

## Execução

In [2]:
A = [77, 33, 84, 5, 39, 28]
ordenado, contador = merge_sort(A.copy())

print('Vetor original:', A)
print('Vetor ordenado:', ordenado)
print('Chamadas:', contador.chamadas)
print('Comparações:', contador.comparacoes)
print('Escritas:', contador.escritas)

display(pd.DataFrame(contador.passos))

Vetor original: [77, 33, 84, 5, 39, 28]
Vetor ordenado: [5, 28, 33, 39, 77, 84]
Chamadas: 11
Comparações: 10
Escritas: 16

             chamada  meio                 subvetor          operação
0   MERGE_SORT(0, 5)     2  [77, 33, 84, 5, 39, 28]           dividir
1   MERGE_SORT(0, 2)     1             [77, 33, 84]           dividir
2   MERGE_SORT(0, 1)     0                 [77, 33]           dividir
3     MERGE(0, 0, 1)     0                 [33, 33]  escrever em A[0]
4     MERGE(0, 1, 2)     1             [33, 77, 84]  escrever em A[0]
5     MERGE(0, 1, 2)     1             [33, 77, 84]  escrever em A[1]
6   MERGE_SORT(3, 5)     4              [5, 39, 28]           dividir
7   MERGE_SORT(3, 4)     3                  [5, 39]           dividir
8     MERGE(3, 3, 4)     3                  [5, 39]  escrever em A[3]
9     MERGE(3, 4, 5)     4              [5, 39, 28]  escrever em A[3]
10    MERGE(3, 4, 5)     4              [5, 28, 28]  escrever em A[4]
11    MERGE(0, 2, 5)     2   [5, 77, 84, 5, 28, 39]  escrever em A[0]
12    MERGE(0, 2, 5)     2   [5, 28, 84, 5, 28, 39]  escrever em A[1]
13    MERGE(0, 2, 5)     2   [5, 28, 33, 5, 28, 39]  escrever em A[2]
14    MERGE(0, 2, 5)     2  [5, 28, 33, 39, 28, 39]  escrever em A[3]

## Tabela N, chamadas, comparações e escritas

In [3]:
linhas = []
for n in range(2, 17):
    A = list(range(n, 0, -1))
    _, contador = merge_sort(A.copy())
    linhas.append({
        'N': n,
        'Chamadas': contador.chamadas,
        'Comparações': contador.comparacoes,
        'Escritas': contador.escritas
    })

display(pd.DataFrame(linhas))

     N  Chamadas  Comparações  Escritas
0    2         3            1         2
1    3         5            2         5
2    4         7            4         8
3    5         9            5        12
4    6        11            7        16
5    7        13            9        20
6    8        15           12        24
7    9        17           13        29
8   10        19           15        34
9   11        21           17        39
10  12        23           20        44
11  13        25           22        49
12  14        27           25        54
13  15        29           28        59
14  16        31           32        64