# Contagem de inversões em um vetor

## Implementação

In [1]:
import pandas as pd

class ContadorInversoes:
    def __init__(self):
        self.passos = []
        self.chamadas = 0


def conta_inversoes(A):
    contador = ContadorInversoes()
    copia = A.copy()
    total = conta_inversoes_rec(copia, 0, len(copia) - 1, contador)
    return total, copia, contador


def conta_inversoes_rec(A, inicio, fim, contador):
    contador.chamadas += 1
    if inicio >= fim:
        return 0

    meio = (inicio + fim) // 2
    inv_esq = conta_inversoes_rec(A, inicio, meio, contador)
    inv_dir = conta_inversoes_rec(A, meio + 1, fim, contador)
    inv_merge = intercala_e_conta(A, inicio, meio, fim, contador)
    return inv_esq + inv_dir + inv_merge


def intercala_e_conta(A, inicio, meio, fim, contador):
    esquerda = A[inicio:meio + 1]
    direita = A[meio + 1:fim + 1]
    i = 0
    j = 0
    k = inicio
    inversoes = 0

    while i < len(esquerda) and j < len(direita):
        if esquerda[i] <= direita[j]:
            A[k] = esquerda[i]
            i += 1
        else:
            A[k] = direita[j]
            novas = len(esquerda) - i
            inversoes += novas
            contador.passos.append({
                'intervalo': f'A[{inicio}:{fim}]',
                'esquerda': esquerda.copy(),
                'direita': direita.copy(),
                'valor_direita': direita[j],
                'novas_inversões': novas,
                'inversões_no_merge': inversoes
            })
            j += 1
        k += 1

    while i < len(esquerda):
        A[k] = esquerda[i]
        i += 1
        k += 1

    while j < len(direita):
        A[k] = direita[j]
        j += 1
        k += 1

    return inversoes

## Execução

In [2]:
A = [4, 1, 3, 2]
total, ordenado, contador = conta_inversoes(A)

print('Vetor original:', A)
print('Vetor ordenado:', ordenado)
print('Total de inversões:', total)
print('Chamadas:', contador.chamadas)

display(pd.DataFrame(contador.passos))

Vetor original: [4, 1, 3, 2]
Vetor ordenado: [1, 2, 3, 4]
Total de inversões: 4
Chamadas: 7

  intervalo esquerda  ... novas_inversões  inversões_no_merge
0    A[0:1]      [4]  ...               1                   1
1    A[2:3]      [3]  ...               1                   1
2    A[0:3]   [1, 4]  ...               1                   1
3    A[0:3]   [1, 4]  ...               1                   2

[4 rows x 6 columns]

## Tabela por exemplo

In [3]:
exemplos = [
    [4, 1, 3, 2],
    [5, 4, 3, 2, 1],
    [1, 2, 3, 4, 5],
    [2, 3, 8, 6, 1]
]

linhas = []
for A in exemplos:
    total, ordenado, contador = conta_inversoes(A)
    linhas.append({'A': A, 'Ordenado': ordenado, 'Inversões': total, 'Chamadas': contador.chamadas})

display(pd.DataFrame(linhas))

                 A         Ordenado  Inversões  Chamadas
0     [4, 1, 3, 2]     [1, 2, 3, 4]          4         7
1  [5, 4, 3, 2, 1]  [1, 2, 3, 4, 5]         10         9
2  [1, 2, 3, 4, 5]  [1, 2, 3, 4, 5]          0         9
3  [2, 3, 8, 6, 1]  [1, 2, 3, 6, 8]          5         9