# Divisão e conquista

## MaxMin

In [1]:
import pandas as pd

class ContadorMaxMin:
    def __init__(self):
        self.chamadas = 0
        self.comparacoes = 0
        self.passos = []


def max_min(A, inf=0, sup=None, contador=None):
    if sup is None:
        sup = len(A) - 1
    if contador is None:
        contador = ContadorMaxMin()

    contador.chamadas += 1

    if inf == sup:
        contador.passos.append({'chamada': f'MAX_MIN({inf}, {sup})', 'subvetor': [A[inf]], 'max': A[inf], 'min': A[inf]})
        return A[inf], A[inf], contador

    if sup - inf == 1:
        contador.comparacoes += 1
        if A[inf] < A[sup]:
            minimo, maximo = A[inf], A[sup]
        else:
            minimo, maximo = A[sup], A[inf]
        contador.passos.append({'chamada': f'MAX_MIN({inf}, {sup})', 'subvetor': A[inf:sup+1], 'max': maximo, 'min': minimo})
        return maximo, minimo, contador

    meio = (inf + sup) // 2
    max1, min1, contador = max_min(A, inf, meio, contador)
    max2, min2, contador = max_min(A, meio + 1, sup, contador)

    contador.comparacoes += 2
    maximo = max1 if max1 > max2 else max2
    minimo = min1 if min1 < min2 else min2

    contador.passos.append({'chamada': f'MAX_MIN({inf}, {sup})', 'subvetor': A[inf:sup+1], 'max': maximo, 'min': minimo})
    return maximo, minimo, contador

## Execução MaxMin

In [2]:
A = [9, 3, 10, 12, 5]
maximo, minimo, contador = max_min(A)

print('Vetor:', A)
print('Máximo:', maximo)
print('Mínimo:', minimo)
print('Chamadas:', contador.chamadas)
print('Comparações:', contador.comparacoes)

display(pd.DataFrame(contador.passos))

Vetor: [9, 3, 10, 12, 5]
Máximo: 12
Mínimo: 3
Chamadas: 5
Comparações: 6

         chamada           subvetor  max  min
0  MAX_MIN(0, 1)             [9, 3]    9    3
1  MAX_MIN(2, 2)               [10]   10   10
2  MAX_MIN(0, 2)         [9, 3, 10]   10    3
3  MAX_MIN(3, 4)            [12, 5]   12    5
4  MAX_MIN(0, 4)  [9, 3, 10, 12, 5]   12    3

## Contagem de pares e ímpares

In [3]:
class ContadorParImpar:
    def __init__(self):
        self.chamadas = 0
        self.passos = []


def conta_pares_impares(A, linf=0, lsup=None, contador=None):
    if lsup is None:
        lsup = len(A) - 1
    if contador is None:
        contador = ContadorParImpar()

    contador.chamadas += 1

    if linf == lsup:
        pares = 1 if A[linf] % 2 == 0 else 0
        impares = 1 - pares
        contador.passos.append({'chamada': f'CONTA({linf}, {lsup})', 'subvetor': [A[linf]], 'pares': pares, 'ímpares': impares})
        return pares, impares, contador

    meio = (linf + lsup) // 2
    pares1, impares1, contador = conta_pares_impares(A, linf, meio, contador)
    pares2, impares2, contador = conta_pares_impares(A, meio + 1, lsup, contador)

    pares = pares1 + pares2
    impares = impares1 + impares2
    contador.passos.append({'chamada': f'CONTA({linf}, {lsup})', 'subvetor': A[linf:lsup+1], 'pares': pares, 'ímpares': impares})
    return pares, impares, contador

## Execução pares e ímpares

In [4]:
A = [4, 7, 2, 9, 10]
pares, impares, contador = conta_pares_impares(A)

print('Vetor:', A)
print('Pares:', pares)
print('Ímpares:', impares)
print('Chamadas:', contador.chamadas)

display(pd.DataFrame(contador.passos))

Vetor: [4, 7, 2, 9, 10]
Pares: 3
Ímpares: 2
Chamadas: 9

       chamada          subvetor  pares  ímpares
0  CONTA(0, 0)               [4]      1        0
1  CONTA(1, 1)               [7]      0        1
2  CONTA(0, 1)            [4, 7]      1        1
3  CONTA(2, 2)               [2]      1        0
4  CONTA(0, 2)         [4, 7, 2]      2        1
5  CONTA(3, 3)               [9]      0        1
6  CONTA(4, 4)              [10]      1        0
7  CONTA(3, 4)           [9, 10]      1        1
8  CONTA(0, 4)  [4, 7, 2, 9, 10]      3        2