# Recursividade

## Vetor simétrico

In [1]:
import pandas as pd

class ContadorSimetrico:
    def __init__(self):
        self.chamadas = 0
        self.passos = []


def simetrico(A, i=0, j=None, contador=None):
    if j is None:
        j = len(A) - 1
    if contador is None:
        contador = ContadorSimetrico()

    contador.chamadas += 1

    if i >= j:
        contador.passos.append({'chamada': f'SIMETRICO({i}, {j})', 'comparação': '-', 'resultado': True})
        return True, contador

    igual = A[i] == A[j]
    contador.passos.append({'chamada': f'SIMETRICO({i}, {j})', 'comparação': f'{A[i]} == {A[j]}', 'resultado': igual})

    if not igual:
        return False, contador

    return simetrico(A, i + 1, j - 1, contador)

## Execução

In [2]:
exemplos = [
    [4, 7, 9, 7, 4],
    [3, 5, 5, 2],
    [1, 2, 2, 1],
    [8]
]

linhas = []
for A in exemplos:
    resultado, contador = simetrico(A)
    linhas.append({'A': A, 'Simétrico': resultado, 'Chamadas': contador.chamadas})

display(pd.DataFrame(linhas))

                 A  Simétrico  Chamadas
0  [4, 7, 9, 7, 4]       True         3
1     [3, 5, 5, 2]      False         1
2     [1, 2, 2, 1]       True         3
3              [8]       True         1

## Passo a passo

In [3]:
A = [4, 7, 9, 7, 4]
resultado, contador = simetrico(A)

print('Vetor:', A)
print('Resultado:', resultado)
print('Chamadas:', contador.chamadas)

display(pd.DataFrame(contador.passos))

Vetor: [4, 7, 9, 7, 4]
Resultado: True
Chamadas: 3

           chamada comparação  resultado
0  SIMETRICO(0, 4)     4 == 4       True
1  SIMETRICO(1, 3)     7 == 7       True
2  SIMETRICO(2, 2)          -       True